# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pruebas Flutter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Clonar repositorio
        uses: actions/checkout@v5

      # Paso 2: Configurar Flutter
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      # Paso 3: Verificar versión de Flutter y Dart
      - name: Verificar versión de Flutter/Dart
        run: flutter --version

      # Paso 4: Instalar dependencias
      - name: Instalar dependencias
        run: flutter pub get

      # Paso 5: Ejecutar tests con cobertura
      - name: Ejecutar pruebas
        run: flutter test --coverage

      # Paso 6: Subir reporte de cobertura
      - name: Subir reporte de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura
          path: coverage/
